### ISSUE TITLE
Attempting to delete a local song from playlist crashes ncspot

### ISSUE THREAD

**Issue by FlynnD273** [hrkfdn/ncspot#1231]
**Describe the bug**
If I use an official Spotify app to add a local file to a playlist then try to use ncspot to delete that song from the playlist, ncspot crashes. 

**To Reproduce**
1. Add a local file to a playlist using an official Spotify app
2. Delete that song from the playlist using ncspot

**Expected behavior**
Either a warning appears saying I can't delete local songs, or it deletes properly. 

**System (please complete the following information):**
 - OS: Ubuntu
 - Terminal: Kitty/Tmux
 - Version: master branch
 - Installed from: source

**Backtrace/Debug log**

Backtrace:
```
   0: ncspot::panic::register_backtrace_panic_handler::{{closure}}
   1: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/alloc/src/boxed.rs:1987:9
   2: std::panicking::rust_panic_with_hook
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:695:13
   3: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:580:13
   4: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/sys_common/backtrace.rs:150:18
   5: rust_begin_unwind
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:578:5
   6: core::panicking::panic_fmt
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/panicking.rs:67:14
   7: ncspot::mpris::MprisManager::new::{{closure}}
   8: tokio::runtime::task::raw::poll
   9: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
  10: tokio::runtime::task::raw::poll
  11: std::sys_common::backtrace::__rust_begin_short_backtrace
  12: core::ops::function::FnOnce::call_once{{vtable.shim}}
  13: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/alloc/src/boxed.rs:1973:9
  14: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/alloc/src/boxed.rs:1973:9
  15: std::sys::unix::thread::Thread::new::thread_start
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/sys/unix/thread.rs:108:17
  16: start_thread
             at ./nptl/./nptl/pthread_create.c:444:8
  17: __GI___clone3
             at ./misc/../sysdeps/unix/sysv/linux/x86_64/clone3.S:81

panicked at 'all branches are disabled and there is no else branch', src/mpris.rs:516:13
```

**Comment by hrkfdn** [comment]
Fixed via #1239
