### ISSUE TITLE
Crash on playlist which contains "unavailable" content

### ISSUE THREAD

**Issue by chaseadam** [hrkfdn/ncspot#349]
Consistent crash on playlist. I *believe* this is due to the playlist containing "unavailable" content (see grey items), but I haven't been able to find/build another playlist to confirm.

![image](https://user-images.githubusercontent.com/333031/102384088-4f20df80-3f9a-11eb-9300-00553c5007e1.png)
https://open.spotify.com/playlist/79PoJdQWUF4AR7nyr1AQnw

In logs shows up as the following example:

```
[2020-12-16][12:24:33] [ncspot::spotify] [INFO] loading track: Track((Hugh Laurie - Winin' Boy Blues (None)))
[2020-12-16][12:24:33] [tokio_core::reactor] [DEBUG] loop poll - 6.251078ms
[2020-12-16][12:24:33] [tokio_core::reactor] [DEBUG] loop time - Instant { tv_sec: 66824, tv_nsec: 191544111 }
[2020-12-16][12:24:33] [tokio_core::reactor] [DEBUG] loop process, 44.319µs
[2020-12-16][12:24:33] [ncspot::spotify] [DEBUG] message received!
[2020-12-16][12:24:33] [ncspot::spotify] [INFO] player loading track: SpotifyId { id: 4287, audio_type: NonPlayable }
[2020-12-16][12:24:33] [ncspot::spotify] [WARN] track is not playable
[2020-12-16][12:24:33] [ncspot] [TRACE] event received: FinishedTrack
```

It does attempt to progress to playing the first playable track and it appears successful when the application exits with error code 101. I believe there is a rust traceback (ran with `RUST_BACKTRACE=full`) but it clears when the ncurses screen exits to the bash prompt:

```
[2020-12-16][12:24:33] [ncspot::spotify] [INFO] loading track: Track((Hugh Laurie - Buddy Bolden's Blues (Some("0JwPDu04a32iQa2PU6ipBn"))))
[2020-12-16][12:24:33] [tokio_core::reactor] [DEBUG] loop poll - 5.408921ms
[2020-12-16][12:24:33] [tokio_core::reactor] [DEBUG] loop time - Instant { tv_sec: 66824, tv_nsec: 197075755 }
[2020-12-16][12:24:33] [tokio_core::reactor] [DEBUG] loop process, 38.568µs
[2020-12-16][12:24:33] [ncspot::spotify] [DEBUG] message received!
...
[2020-12-16][12:24:33] [ncspot::spotify] [DEBUG] librespot player event: Playing { play_request_id: 0, track_id: SpotifyId { id: 32072090120953601862759006913652540673, audio_type: Track }, position_ms: 0, duration_ms: 192800 }
[2020-12-16][12:24:33] [tokio_core::reactor] [DEBUG] loop poll - 2.8µs
[2020-12-16][12:24:33] [tokio_core::reactor] [DEBUG] loop time - Instant { tv_sec: 66824, tv_nsec: 291188278 }
[2020-12-16][12:24:33] [tokio_core::reactor] [DEBUG] loop process, 19.64µs
[2020-12-16][12:24:33] [ncspot] [TRACE] event received: Playing
[2020-12-16][12:24:33] [tokio_core::reactor] [DEBUG] loop poll - 3.146059ms
[2020-12-16][12:24:33] [tokio_core::reactor] [DEBUG] loop time - Instant { tv_sec: 66824, tv_nsec: 294360369 }
[2020-12-16][12:24:33] [tokio_core::reactor] [DEBUG] loop process, 25.946µs
```

**Comment by JojiiOfficial** [comment]
Those logs are only debug information. Could you provide the rust backtrace? You probably have to add the debug-file-flag to get more information.

**Comment by chaseadam** [comment]
What is the best way to capture the rust backtrace. It does not appear in the file produced by `ncspot -d /tmp/foo`.

I believe there is a rust traceback (ran with RUST_BACKTRACE=full and RUST_BACKTRACE=1) but it clears when the ncurses screen exits to the bash prompt.

**Comment by hrkfdn** [comment]
You'll want the stderr output, e.g. by running `RUST_BACKTRACE=full cargo run 2>/tmp/stderr.log`

**Comment by chaseadam** [comment]
got it with `RUST_BACKTRACE=full cargo run 2>/tmp/stderr.log`

Aside: The "exit" of the app does *not* occur (plays the first "available" entry it hits in the playlist) when I run it with stderr redirected, but it *does* exit if it is not redirected.

```
    Finished dev [unoptimized + debuginfo] target(s) in 3m 54s
     Running `target/debug/ncspot`
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: "Object path was not valid: \'/org/ncspot/spotify/local/Hugh+Laurie/Let+Them+Talk/You+Don%27t+Know+My+Mind/219\'"', /home/achasen/.cargo/registry/src/github.com-1ecc6299db9ec823/dbus-0.9.0/src/strings.rs:187:1
stack backtrace:
   0:     0x55a50ac2b940 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hc5cc02b3e453225b
   1:     0x55a50ac5222c - core::fmt::write::h5437b03347b2ec7a
   2:     0x55a50ac238f5 - std::io::Write::write_fmt::h16241c6ed218e16f
   3:     0x55a50ac2de2d - std::panicking::default_hook::{{closure}}::h345f4275bb854b6c
   4:     0x55a50ac2dad8 - std::panicking::default_hook::he532b712c71e2106
   5:     0x55a50ac2e511 - std::panicking::rust_panic_with_hook::hf0f7347c753b38c2
   6:     0x55a50ac2e0b9 - std::panicking::begin_panic_handler::{{closure}}::h274b8a0752683642
   7:     0x55a50ac2bdac - std::sys_common::backtrace::__rust_end_short_backtrace::hdb383c60eb8b212f
   8:     0x55a50ac2e079 - rust_begin_unwind
   9:     0x55a50ac4fdb1 - core::panicking::panic_fmt::h8d2c19297fe96b44
  10:     0x55a50ac4fbd3 - core::option::expect_none_failed::h1a6f64ce49780e5b
  11:     0x55a509658870 - core::result::Result<T,E>::unwrap::h7868986e089220cd
                               at /builddir/build/BUILD/rustc-1.48.0-src/library/core/src/result.rs:973
  12:     0x55a50967c958 - <dbus::strings::Path as core::convert::From<alloc::string::String>>::from::h4572d09bb2c7fd7b
                               at /home/achasen/.cargo/registry/src/github.com-1ecc6299db9ec823/dbus-0.9.0/src/strings.rs:101
  13:     0x55a508f71fa4 - ncspot::mpris::get_metadata::hbd1c1a32085c618b
                               at /home/achasen/git/ncspot/src/mpris.rs:46
  14:     0x55a508f765c4 - ncspot::mpris::run_dbus_server::haabcaef3bc1c64cb
                               at /home/achasen/git/ncspot/src/mpris.rs:663
  15:     0x55a508f1f14a - ncspot::mpris::MprisManager::new::{{closure}}::h3f334fe1910b4e49
                               at /home/achasen/git/ncspot/src/mpris.rs:693
  16:     0x55a508f671f3 - std::sys_common::backtrace::__rust_begin_short_backtrace::h3a37df462ef75624
                               at /builddir/build/BUILD/rustc-1.48.0-src/library/std/src/sys_common/backtrace.rs:137
  17:     0x55a508fd07d2 - std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}}::h7c282ce0e6e35b3c
                               at /builddir/build/BUILD/rustc-1.48.0-src/library/std/src/thread/mod.rs:464
  18:     0x55a508f216b2 - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h590745b6ee0d9f07
                               at /builddir/build/BUILD/rustc-1.48.0-src/library/std/src/panic.rs:308
  19:     0x55a5091b2c60 - std::panicking::try::do_call::h26a6a049615eb975
                               at /builddir/build/BUILD/rustc-1.48.0-src/library/std/src/panicking.rs:381
  20:     0x55a5091b44bd - __rust_try
  21:     0x55a5091b0be0 - std::panicking::try::h1bef893c8afba89e
                               at /builddir/build/BUILD/rustc-1.48.0-src/library/std/src/panicking.rs:345
  22:     0x55a508f21ae2 - std::panic::catch_unwind::h0d44a4a0a4815049
                               at /builddir/build/BUILD/rustc-1.48.0-src/library/std/src/panic.rs:382
  23:     0x55a508fcd421 - std::thread::Builder::spawn_unchecked::{{closure}}::h9a530cb833355728
                               at /builddir/build/BUILD/rustc-1.48.0-src/library/std/src/thread/mod.rs:463
  24:     0x55a50927636e - core::ops::function::FnOnce::call_once{{vtable.shim}}::hac70a13b189a8d7a
                               at /builddir/build/BUILD/rustc-1.48.0-src/library/core/src/ops/function.rs:227
  25:     0x55a50ac3591a - std::sys::unix::thread::Thread::new::thread_start::h05696559b46a3b75
  26:     0x7ffbeaf243f9 - start_thread
  27:     0x7ffbeb184903 - __clone
  28:                0x0 - <unknown>
```

**Comment by JojiiOfficial** [comment]
Confirmed. I'm having the same issue with this playlist. With some songs it crashes, with others it just gives some weird display bugs and with one I got a panic like looking error printed out without ncspot getting exited.

**Comment by hrkfdn** [comment]
Hi there, thanks for the detailed report and comments. It was trying to announce track IDs for unplayable tracks via MPRIS, which should be fixed now. Does this solve your issue?

I guess we could filter out unplayable tracks in playlists entirely, too. But I'm not 100% certain yet.

**Comment by JojiiOfficial** [comment]
Would it be possible to gray them out like the official client does? I think ncspot should display _available_ songs in the same way the official client does.
