### ISSUE TITLE
thread '<unnamed>' panicked at 'Authentication failed with reason: BadCredentials'

### ISSUE THREAD

**Issue by dangelov** [hrkfdn/ncspot#358]
I installed `ncspot` as a snap package, then ran it with:

```
$ ncspot
```

The first time around I provided the wrong password, and I was prompted again for a new one. Second time around I again entered the wrong one and saw this in my terminal:

```
thread '<unnamed>' panicked at 'Authentication failed with reason: BadCredentials', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/librespot-core-0.1.3/src/connection/mod.rs:121:21
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Killed it with Ctrl+C and restarted it, then it worked after I passed the correct credentials.

**Comment by hrkfdn** [comment]
Hmm, I can't reproduce this unfortunately. Is this with Facebook or regular auth?

When I enter another invalid login after the first prompt the prompt appears again until I login with my correct credentials. A backtrace would be helpful, e.g. via `ncspot 2> /tmp/backtrace.log`. The backtrace will be in `/tmp/backtrace.log`.

**Comment by dangelov** [comment]
I just attempted to clear my login credentials, and because I installed via snap, removed the files in the location I found via #65:
```
dangelov@dangelov-popos:~/snap/ncspot/current/.config/ncspot$ cat config.toml 
dangelov@dangelov-popos:~/snap/ncspot/current/.config/ncspot$ ls
config.toml
dangelov@dangelov-popos:~/snap/ncspot/current/.config/ncspot$ 
```

When I start ncspot, I am still logged in. Is there any other location for configs or cache that I need to clear?

**Comment by Bettehem** [comment]
> I just attempted to clear my login credentials, and because I installed via snap, removed the files in the location I found via #65:
> 
> ```
> dangelov@dangelov-popos:~/snap/ncspot/current/.config/ncspot$ cat config.toml 
> dangelov@dangelov-popos:~/snap/ncspot/current/.config/ncspot$ ls
> config.toml
> dangelov@dangelov-popos:~/snap/ncspot/current/.config/ncspot$ 
> ```
> 
> When I start ncspot, I am still logged in. Is there any other location for configs or cache that I need to clear?

The cache is stored under `~/.cache/ncspot`

**Comment by dangelov** [comment]
Thank you. In case anyone arrives here Googling, the location of the cache when installed as a snap package is:
`~/snap/ncspot/current/.cache`

Anyway, here's the log
```
thread '<unnamed>' panicked at 'Authentication failed with reason: BadCredentials', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/librespot-core-0.1.3/src/connection/mod.rs:121:21
stack backtrace:
   0:     0x55bba0e55c50 - std::backtrace_rs::backtrace::libunwind::trace::h72c2fb8038f1bbee
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/../../backtrace/src/backtrace/libunwind.rs:96
   1:     0x55bba0e55c50 - std::backtrace_rs::backtrace::trace_unsynchronized::h1e3b084883f1e78c
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/../../backtrace/src/backtrace/mod.rs:66
   2:     0x55bba0e55c50 - std::sys_common::backtrace::_print_fmt::h3bf6a7ebf7f0394a
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:79
   3:     0x55bba0e55c50 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h2e8cb764b7fe02e7
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:58
   4:     0x55bba0e7c44c - core::fmt::write::h7a1184eaee6a8644
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/fmt/mod.rs:1080
   5:     0x55bba0e4de82 - std::io::Write::write_fmt::haeeb374d93a67eac
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/io/mod.rs:1516
   6:     0x55bba0e5813d - std::sys_common::backtrace::_print::h1d14a7f6ad632dc8
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:61
   7:     0x55bba0e5813d - std::sys_common::backtrace::print::h301abac8bb2e3e81
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:48
   8:     0x55bba0e5813d - std::panicking::default_hook::{{closure}}::hde0cb80358a6920a
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:208
   9:     0x55bba0e57de8 - std::panicking::default_hook::h9b1a691049a0ec8f
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:227
  10:     0x55bba0e58821 - std::panicking::rust_panic_with_hook::h2bdec87b60580584
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:577
  11:     0x55bba0e583c9 - std::panicking::begin_panic_handler::{{closure}}::h101ca09d9df5db47
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:484
  12:     0x55bba0e560bc - std::sys_common::backtrace::__rust_end_short_backtrace::h3bb85654c20113ca
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:153
  13:     0x55bba0e58389 - rust_begin_unwind
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:483
  14:     0x55bba0e5833b - std::panicking::begin_panic_fmt::hf0503558fbe5b251
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:437
  15:     0x55bba0af21d4 - futures::future::chain::Chain<A,B,C>::poll::h497628e4c8ef354b
  16:     0x55bba0b029f9 - <futures::future::and_then::AndThen<A,B,F> as futures::future::Future>::poll::h0816ebc0d0be6b2e
  17:     0x55bba0af73f6 - futures::future::chain::Chain<A,B,C>::poll::hbc64c52e1adc559e
  18:     0x55bba0b40c59 - <futures::future::map::Map<A,F> as futures::future::Future>::poll::h31e3a01d5e574936
  19:     0x55bba0557ed9 - futures::task_impl::std::set::h8003ae808de6dca5
  20:     0x55bba0540f7b - <futures::future::lazy::Lazy<F,R> as futures::future::Future>::poll::h7771ede468f4598c
  21:     0x55bba0558504 - futures::task_impl::std::set::hfd7b0797d58d6c0b
  22:     0x55bba062da4a - std::thread::local::LocalKey<T>::with::h8d80e73fc746aa15
  23:     0x55bba051d5fd - tokio_timer::timer::handle::with_default::hefc2091e1c1405cf
  24:     0x55bba062d7b2 - std::thread::local::LocalKey<T>::with::h88a9dcbfc63ff55e
  25:     0x55bba0568dc3 - scoped_tls::ScopedKey<T>::set::h0ea5c837f3774ecf
  26:     0x55bba05fdd80 - tokio_core::reactor::Core::run::hc9b5bcf774883744
  27:     0x55bba056df8e - std::sys_common::backtrace::__rust_begin_short_backtrace::h73cf4cee03b68779
  28:     0x55bba0576dd4 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h207ac07c41d8d20f
  29:     0x55bba0e5fc1a - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::hbb39a3e615f69ef9
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/alloc/src/boxed.rs:1042
  30:     0x55bba0e5fc1a - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h79630a683aed732c
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/alloc/src/boxed.rs:1042
  31:     0x55bba0e5fc1a - std::sys::unix::thread::Thread::new::thread_start::h4afaeade0da13617
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys/unix/thread.rs:87
  32:     0x7faddd5d26db - start_thread
  33:     0x7fadddca971f - __clone
  34:                0x0 - <unknown>
thread '<unnamed>' panicked at 'Authentication failed with reason: BadCredentials', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/librespot-core-0.1.3/src/connection/mod.rs:121:21
stack backtrace:
   0:     0x55bba0e55c50 - std::backtrace_rs::backtrace::libunwind::trace::h72c2fb8038f1bbee
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/../../backtrace/src/backtrace/libunwind.rs:96
   1:     0x55bba0e55c50 - std::backtrace_rs::backtrace::trace_unsynchronized::h1e3b084883f1e78c
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/../../backtrace/src/backtrace/mod.rs:66
   2:     0x55bba0e55c50 - std::sys_common::backtrace::_print_fmt::h3bf6a7ebf7f0394a
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:79
   3:     0x55bba0e55c50 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h2e8cb764b7fe02e7
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:58
   4:     0x55bba0e7c44c - core::fmt::write::h7a1184eaee6a8644
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/fmt/mod.rs:1080
   5:     0x55bba0e4de82 - std::io::Write::write_fmt::haeeb374d93a67eac
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/io/mod.rs:1516
   6:     0x55bba0e5813d - std::sys_common::backtrace::_print::h1d14a7f6ad632dc8
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:61
   7:     0x55bba0e5813d - std::sys_common::backtrace::print::h301abac8bb2e3e81
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:48
   8:     0x55bba0e5813d - std::panicking::default_hook::{{closure}}::hde0cb80358a6920a
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:208
   9:     0x55bba0e57de8 - std::panicking::default_hook::h9b1a691049a0ec8f
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:227
  10:     0x55bba0e58821 - std::panicking::rust_panic_with_hook::h2bdec87b60580584
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:577
  11:     0x55bba0e583c9 - std::panicking::begin_panic_handler::{{closure}}::h101ca09d9df5db47
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:484
  12:     0x55bba0e560bc - std::sys_common::backtrace::__rust_end_short_backtrace::h3bb85654c20113ca
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:153
  13:     0x55bba0e58389 - rust_begin_unwind
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:483
  14:     0x55bba0e5833b - std::panicking::begin_panic_fmt::hf0503558fbe5b251
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:437
  15:     0x55bba0af21d4 - futures::future::chain::Chain<A,B,C>::poll::h497628e4c8ef354b
  16:     0x55bba0b029f9 - <futures::future::and_then::AndThen<A,B,F> as futures::future::Future>::poll::h0816ebc0d0be6b2e
  17:     0x55bba0af73f6 - futures::future::chain::Chain<A,B,C>::poll::hbc64c52e1adc559e
  18:     0x55bba0b40c59 - <futures::future::map::Map<A,F> as futures::future::Future>::poll::h31e3a01d5e574936
  19:     0x55bba0557ed9 - futures::task_impl::std::set::h8003ae808de6dca5
  20:     0x55bba0540f7b - <futures::future::lazy::Lazy<F,R> as futures::future::Future>::poll::h7771ede468f4598c
  21:     0x55bba0558504 - futures::task_impl::std::set::hfd7b0797d58d6c0b
  22:     0x55bba062da4a - std::thread::local::LocalKey<T>::with::h8d80e73fc746aa15
  23:     0x55bba051d5fd - tokio_timer::timer::handle::with_default::hefc2091e1c1405cf
  24:     0x55bba062d7b2 - std::thread::local::LocalKey<T>::with::h88a9dcbfc63ff55e
  25:     0x55bba0568dc3 - scoped_tls::ScopedKey<T>::set::h0ea5c837f3774ecf
  26:     0x55bba05fdd80 - tokio_core::reactor::Core::run::hc9b5bcf774883744
  27:     0x55bba056df8e - std::sys_common::backtrace::__rust_begin_short_backtrace::h73cf4cee03b68779
  28:     0x55bba0576dd4 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h207ac07c41d8d20f
  29:     0x55bba0e5fc1a - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::hbb39a3e615f69ef9
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/alloc/src/boxed.rs:1042
  30:     0x55bba0e5fc1a - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h79630a683aed732c
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/alloc/src/boxed.rs:1042
  31:     0x55bba0e5fc1a - std::sys::unix::thread::Thread::new::thread_start::h4afaeade0da13617
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys/unix/thread.rs:87
  32:     0x7faddd5d26db - start_thread
  33:     0x7fadddca971f - __clone
  34:                0x0 - <unknown>
thread '<unnamed>' panicked at 'Authentication failed with reason: BadCredentials', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/librespot-core-0.1.3/src/connection/mod.rs:121:21
stack backtrace:
   0:     0x55bba0e55c50 - std::backtrace_rs::backtrace::libunwind::trace::h72c2fb8038f1bbee
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/../../backtrace/src/backtrace/libunwind.rs:96
   1:     0x55bba0e55c50 - std::backtrace_rs::backtrace::trace_unsynchronized::h1e3b084883f1e78c
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/../../backtrace/src/backtrace/mod.rs:66
   2:     0x55bba0e55c50 - std::sys_common::backtrace::_print_fmt::h3bf6a7ebf7f0394a
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:79
   3:     0x55bba0e55c50 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h2e8cb764b7fe02e7
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:58
   4:     0x55bba0e7c44c - core::fmt::write::h7a1184eaee6a8644
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/fmt/mod.rs:1080
   5:     0x55bba0e4de82 - std::io::Write::write_fmt::haeeb374d93a67eac
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/io/mod.rs:1516
   6:     0x55bba0e5813d - std::sys_common::backtrace::_print::h1d14a7f6ad632dc8
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:61
   7:     0x55bba0e5813d - std::sys_common::backtrace::print::h301abac8bb2e3e81
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:48
   8:     0x55bba0e5813d - std::panicking::default_hook::{{closure}}::hde0cb80358a6920a
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:208
   9:     0x55bba0e57de8 - std::panicking::default_hook::h9b1a691049a0ec8f
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:227
  10:     0x55bba0e58821 - std::panicking::rust_panic_with_hook::h2bdec87b60580584
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:577
  11:     0x55bba0e583c9 - std::panicking::begin_panic_handler::{{closure}}::h101ca09d9df5db47
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:484
  12:     0x55bba0e560bc - std::sys_common::backtrace::__rust_end_short_backtrace::h3bb85654c20113ca
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:153
  13:     0x55bba0e58389 - rust_begin_unwind
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:483
  14:     0x55bba0e5833b - std::panicking::begin_panic_fmt::hf0503558fbe5b251
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:437
  15:     0x55bba0af21d4 - futures::future::chain::Chain<A,B,C>::poll::h497628e4c8ef354b
  16:     0x55bba0b029f9 - <futures::future::and_then::AndThen<A,B,F> as futures::future::Future>::poll::h0816ebc0d0be6b2e
  17:     0x55bba0af73f6 - futures::future::chain::Chain<A,B,C>::poll::hbc64c52e1adc559e
  18:     0x55bba0b40c59 - <futures::future::map::Map<A,F> as futures::future::Future>::poll::h31e3a01d5e574936
  19:     0x55bba0557ed9 - futures::task_impl::std::set::h8003ae808de6dca5
  20:     0x55bba0540f7b - <futures::future::lazy::Lazy<F,R> as futures::future::Future>::poll::h7771ede468f4598c
  21:     0x55bba0558504 - futures::task_impl::std::set::hfd7b0797d58d6c0b
  22:     0x55bba062da4a - std::thread::local::LocalKey<T>::with::h8d80e73fc746aa15
  23:     0x55bba051d5fd - tokio_timer::timer::handle::with_default::hefc2091e1c1405cf
  24:     0x55bba062d7b2 - std::thread::local::LocalKey<T>::with::h88a9dcbfc63ff55e
  25:     0x55bba0568dc3 - scoped_tls::ScopedKey<T>::set::h0ea5c837f3774ecf
  26:     0x55bba05fdd80 - tokio_core::reactor::Core::run::hc9b5bcf774883744
  27:     0x55bba056df8e - std::sys_common::backtrace::__rust_begin_short_backtrace::h73cf4cee03b68779
  28:     0x55bba0576dd4 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h207ac07c41d8d20f
  29:     0x55bba0e5fc1a - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::hbb39a3e615f69ef9
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/alloc/src/boxed.rs:1042
  30:     0x55bba0e5fc1a - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h79630a683aed732c
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/alloc/src/boxed.rs:1042
  31:     0x55bba0e5fc1a - std::sys::unix::thread::Thread::new::thread_start::h4afaeade0da13617
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys/unix/thread.rs:87
  32:     0x7faddd5d26db - start_thread
  33:     0x7fadddca971f - __clone
  34:                0x0 - <unknown>
Didn't obtain any credentials
```
