### ISSUE TITLE
ncspot panics after sleep

### ISSUE THREAD

**Issue by itielsa** [hrkfdn/ncspot#422]
many times (but not always), ncspot will close itself with the first action that i will try after waking from sleep.
it may be duplicate of #192. 

## system
- running on arch linux. 
- ncspot version 0.4.0 (but the error is not new)

## relevant log

> [11:48:10] [ncspot::ui::layout] [DEBUG] layout: new screen selected: Some("search")
[2021-02-08][11:48:13] [tokio_core::reactor] [DEBUG] loop poll - 178.304110145s
[2021-02-08][11:48:13] [tokio_core::reactor] [DEBUG] loop time - Instant { tv_sec: 139939, tv_nsec: 651104616 }
[2021-02-08][11:48:13] [tokio_core::reactor] [DEBUG] loop process, 121.689µs
[2021-02-08][11:48:13] [ncspot::spotify] [DEBUG] message received!
[2021-02-08][11:48:13] [tokio_reactor::registration] [DEBUG] scheduling Read for: 1
[2021-02-08][11:48:13] [tokio_io::_tokio_codec::framed_write] [TRACE] flushing framed transport
[2021-02-08][11:48:13] [tokio_io::_tokio_codec::framed_write] [TRACE] writing; remaining=342
[2021-02-08][11:48:13] [tokio_io::_tokio_codec::framed_write] [TRACE] framed transport flushed
[2021-02-08][11:48:13] [tokio_core::reactor] [DEBUG] loop poll - 184.603µs
[2021-02-08][11:48:13] [tokio_core::reactor] [DEBUG] loop time - Instant { tv_sec: 139939, tv_nsec: 651537617 }
[2021-02-08][11:48:13] [tokio_core::reactor] [DEBUG] loop process, 25.579µs
[2021-02-08][11:48:13] [tokio_reactor] [TRACE] event Readable | Writable | Error | Hup Token(4194305)
[2021-02-08][11:48:13] [tokio_reactor] [TRACE] loop process - 1 events, 0.000s
[2021-02-08][11:48:13] [librespot_core::session] [DEBUG] Invalidating session[3]
[2021-02-08][11:48:13] [librespot_core::session] [DEBUG] drop Dispatch
[2021-02-08][11:48:13] [mio::poll] [TRACE] deregistering handle with poller
[2021-02-08][11:48:13] [tokio_reactor] [DEBUG] dropping I/O source: 1
[2021-02-08][11:48:13] [librespot_core::session] [ERROR] Os { code: 104, kind: ConnectionReset, message: "Connection reset by peer" }
[2021-02-08][11:48:13] [tokio_core::reactor] [DEBUG] loop poll - 82.837131ms
[2021-02-08][11:48:13] [tokio_core::reactor] [DEBUG] loop time - Instant { tv_sec: 139939, tv_nsec: 734413061 }
[2021-02-08][11:48:13] [tokio_core::reactor] [DEBUG] loop process, 26.909µs
[2021-02-08][11:48:13] [librespot_playback::player] [DEBUG] Shutting down player thread ...
[2021-02-08][11:48:13] [librespot_playback::player] [DEBUG] drop PlayerInternal[3]
[2021-02-08][11:48:13] [librespot_core::session] [DEBUG] drop Session[3]
[2021-02-08][11:48:13] [librespot::component] [DEBUG] drop AudioKeyManager
[2021-02-08][11:48:13] [librespot::component] [DEBUG] drop ChannelManager
[2021-02-08][11:48:13] [librespot::component] [DEBUG] drop MercuryManager
[2021-02-08][11:48:13] [librespot_playback::player] [DEBUG] PlayerInternal thread finished.
[2021-02-08][11:48:13] [ncspot::spotify] [ERROR] worker thread died, requesting restart
[2021-02-08][11:48:13] [tokio_threadpool::pool] [TRACE] shutdown; state=pool::State { lifecycle: Running, num_futures: 0 }
[2021-02-08][11:48:13] [tokio_threadpool::pool] [TRACE]   -> transitioned to shutdown
[2021-02-08][11:48:13] [tokio_threadpool::pool] [TRACE]   -> shutting down workers

### stderr:
>  thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Canceled', src/spotify.rs:533:59
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by hrkfdn** [comment]
Hey and thanks for the report.

> note: run with RUST_BACKTRACE=1 environment variable to display a backtrace

Could you do this and submit the stderr output with the backtrace the next time it happens?

**Comment by itielsa** [comment]
This is the stderr with RUST_BACKTRACE=1:
> thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Canceled', src/spotify.rs:533:59                             
stack backtrace:                                                               
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

and this is stderr with RUST_BACKTRACE=full:
> thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Canceled', src/spotify.rs:533:59
stack backtrace:
   0:     0x55bf759da170 - <unknown>
   1:     0x55bf75a01f6c - <unknown>
   2:     0x55bf759d2285 - <unknown>
   3:     0x55bf759dc855 - <unknown>
   4:     0x55bf759dc4f8 - <unknown>
   5:     0x55bf759dcff1 - <unknown>
   6:     0x55bf759dcb37 - <unknown>
   7:     0x55bf759da62c - <unknown>
   8:     0x55bf759dca99 - <unknown>
   9:     0x55bf759ff3d1 - <unknown>
  10:     0x55bf759ff1f3 - <unknown>
  11:     0x55bf7504c1a8 - <unknown>
  12:     0x55bf75198cc8 - <unknown>
  13:     0x55bf751c7cb6 - <unknown>
  14:     0x55bf75935ce8 - <unknown>
  15:     0x55bf7506137f - <unknown>
  16:     0x55bf751a423c - <unknown>
  17:     0x55bf750c06e3 - <unknown>
  18:     0x55bf7507bbd9 - <unknown>
  19:     0x55bf759dd507 - <unknown>
  20:     0x55bf751a5542 - main
  21:     0x7f131a48bb25 - __libc_start_main
  22:     0x55bf74fa408e - <unknown>
  23:                0x0 - <unknown>

Thanks.

**Comment by hrkfdn** [comment]
Ah, this is a release build. The release build is lacking debug symbols so won't have very useful backtraces. It needs to be done with a debug build instead (e.g. created with `cargo build`).

**Comment by itielsa** [comment]
I should have thought about it..

anyway, here it is:

[stderr](https://github.com/hrkfdn/ncspot/files/5952610/stderr.debug.log)

**Comment by albertskog** [comment]
Not sure if this is the same issue, but I also often have panicking when returning to my computer. Seems to be on different lines in my case. Will try to capture a backtrace. (Also, is this how the crash message is expected to appear?)
![ncspot-bug](https://user-images.githubusercontent.com/706444/130443945-914fc389-53ab-4223-9032-1e0ec4039ff6.png)

**Comment by albertskog** [comment]
Here is a backtrace, sorry for only pasting an image, but the ncspot exits and the text disappears when I click to highlight it..
![ncspot_bug_backtrace](https://user-images.githubusercontent.com/706444/130581054-6494fcd9-7f58-4f07-9999-b9f49776d1f4.png)

**Comment by gonced8** [comment]
I'm experiencing the same error.
Debian 11
ncspot 0.8.1

**Comment by chaseadam** [comment]
From the `unauthorized` in the log, I would guess there is some additional handling of expired authentication tokens necessary. I wonder if this is what I am seeing with crashes from a long running (inactive?) ncspot process.
