### ISSUE TITLE
Err Value: Invalid number of channels

### ISSUE THREAD

**Issue by elmoritz** [hrkfdn/ncspot#484]
**Describe the bug**
The App Crashes every Time a song is selected.
This is the first time I use ncspot. 
I installed it through brew on macos Big Sur.
Also tried to build it myself, but sadly with the same result

**To Reproduce**
1. Install ncspot and open ncspot
1.a use `brew install ncspot` and use `ncspot` to start
1.b clone repo and run `cargo run --no-default-features --features portaudio_backend,cursive/pancurses-backend`
2. login to premium account
3. Click on ANY Song
    `thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Invalid number of channels', /Users/brew/Library/Caches/Homebrew/cargo_cache/registry/src/github.com-1ecc6299db9ec823/librespot-playback-0.1.6/src/audio_backend/portaudio.rs:86:18`

**Expected behavior**
Song should be playing AND app should not crash

**System (please complete the following information):**
 - OS: macOS Big Sur 11.2
 - Terminal: terminal and iTerm2(zsh)
 - Version: 0.5.0(via brew), `master` branch (via git clone)
 - Installed from: brew and cargo

**Backtrace/Debug log**
```
━||PaMacCore (AUHAL)|| Error on line 1316: err='-66748', msg=Unknown Error┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉
 ◼  HBz, Sarah Lahn - Friday Night Lights      thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Internal PortAudio error', /Users/mrpink/.cargo/registry/src/github.com-1ecc6299db9ec823/librespot-playback-0.1.6/src/audio_backend/portaudio.rs:86:18        00:00 / 02:55 [100%]
        stack backtrace:
0:         0x10b1940be - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h04abbaabf148650a
1:         0x10b1d4f6e - core::fmt::write::h14dac7cadec1cc70
2:         0x10b193a7a - std::io::Write::write_fmt::hfaf2e10dfdcc61d8
3:         0x10b1b1979 - std::panicking::default_hook::{{closure}}::h350fee0bf60f2674
4:         0x10b1b14eb - std::panicking::default_hook::h0b4e3bc46e6dcb8d
5:         0x10b1b1f0a - std::panicking::rust_panic_with_hook::h8cdc0a575f4a5a7b
6:         0x10b194885 - std::panicking::begin_panic_handler::{{closure}}::h7a7b30fd1c313876
7:         0x10b194208 - std::sys_common::backtrace::__rust_end_short_backtrace::h2e099be83c81509d
8:         0x10b1b1a83 - _rust_begin_unwind
9:         0x10b1e8c6f - core::panicking::panic_fmt::h4f63e4f6b62b650b
10:        0x10b1e87d5 - core::result::unwrap_failed::hc2a56d017349147e
11:        0x10a58b521 - core::result::Result<T,E>::unwrap::hd28dff6404479b99
    at /private/tmp/rust-20210325-88347-hh2ixd/rustc-1.51.0-src/library/core/src/result.rs:1037:23
12:        0x10a5d119c - <librespot_playback::audio_backend::portaudio::PortAudioSink as librespot_playback::audio_backend::Sink>::start::hd2cb0dac36214927
    at /Users/mrpink/.cargo/registry/src/github.com-1ecc6299db9ec823/librespot-playback-0.1.6/src/audio_backend/portaudio.rs:78:17
13:        0x10a57edc2 - librespot_playback::player::PlayerInternal::ensure_sink_running::h24988db67ededa5b
    at /Users/mrpink/.cargo/registry/src/github.com-1ecc6299db9ec823/librespot-playback-0.1.6/src/player.rs:941:19
14:        0x10a58004d - librespot_playback::player::PlayerInternal::start_playback::hf3efc6a17a5551ad
    at /Users/mrpink/.cargo/registry/src/github.com-1ecc6299db9ec823/librespot-playback-0.1.6/src/player.rs:1106:13
15:        0x10a57d9b0 - <librespot_playback::player::PlayerInternal as futures::future::Future>::poll::haabdb7656a8ab742
    at /Users/mrpink/.cargo/registry/src/github.com-1ecc6299db9ec823/librespot-playback-0.1.6/src/player.rs:772:25
16:        0x109a067f1 - futures::task_impl::Spawn<T>::poll_future_notify::{{closure}}::hef2cfeb2ad29cbfd
  at /Users/mrpink/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.31/src/task_impl/mod.rs:329:45
17:        0x109a073ef - futures::task_impl::Spawn<T>::enter::{{closure}}::hf92cb1a2f30f2bf7
    at /Users/mrpink/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.31/src/task_impl/mod.rs:399:27
18:        0x109be4cfe - futures::task_impl::std::set::h672035885f4f2379
    at /Users/mrpink/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.31/src/task_impl/std/mod.rs:86:13
19:        0x109a07230 - futures::task_impl::Spawn<T>::enter::hfe76ef9ef64fcfaa
    at /Users/mrpink/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.31/src/task_impl/mod.rs:399:9
20:        0x109a06010 - futures::task_impl::Spawn<T>::poll_fn_notify::h2dfc5460969d2840
    at /Users/mrpink/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.31/src/task_impl/mod.rs:291:9
21:        0x109a065a9 - futures::task_impl::Spawn<T>::poll_future_notify::h26cc00d237bcf2b2
    at /Users/mrpink/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.31/src/task_impl/mod.rs:329:9
22:        0x109be549c - futures::task_impl::std::<impl futures::task_impl::Spawn<F>>::wait_future::{{closure}}::hb448a7538070e2ac
    at /Users/mrpink/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.31/src/task_impl/std/mod.rs:239:23
23:        0x109be47d0 - futures::task_impl::std::ThreadNotify::with_current::{{closure}}::hcdb09b67c22d00c4
    at /Users/mrpink/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.31/src/task_impl/std/mod.rs:486:45
24:        0x109c57986 - std::thread::local::LocalKey<T>::try_with::h714b3223fe4f5527
    at /private/tmp/rust-20210325-88347-hh2ixd/rustc-1.51.0-src/library/std/src/thread/local.rs:272:16
25:        0x109c57165 - std::thread::local::LocalKey<T>::with::h77e647e6a0c85f60
    at /private/tmp/rust-20210325-88347-hh2ixd/rustc-1.51.0-src/library/std/src/thread/local.rs:248:9
26:        0x109be4793 - futures::task_impl::std::ThreadNotify::with_current::hfeed6d58fe094902
  at /Users/mrpink/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.31/src/task_impl/std/mod.rs:486:9
27:        0x109a0744d - futures::task_impl::std::<impl futures::task_impl::Spawn<F>>::wait_future::hf06727c56e9217b3
    at /Users/mrpink/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.31/src/task_impl/std/mod.rs:236:9
28:        0x1099fe45c - futures::future::Future::wait::hef39f9dfc76794d1
    at /Users/mrpink/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.31/src/future/mod.rs:300:9
29:        0x1099fe181 - librespot_playback::player::Player::new::{{closure}}::h5949d0ee9c64f71d
    at /Users/mrpink/.cargo/registry/src/github.com-1ecc6299db9ec823/librespot-playback-0.1.6/src/player.rs:262:21
30:        0x109abbd7a - std::sys_common::backtrace::__rust_begin_short_backtrace::h19cf7202f90606f9
    at /private/tmp/rust-20210325-88347-hh2ixd/rustc-1.51.0-src/library/std/src/sys_common/backtrace.rs:125:18
31:        0x109af6ec1 - std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}}::he6e9049d470b4f16
    at /private/tmp/rust-20210325-88347-hh2ixd/rustc-1.51.0-src/library/std/src/thread/mod.rs:474:17
32:        0x109bfe8d1 - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::he9a229c23fd52509
    at /private/tmp/rust-20210325-88347-hh2ixd/rustc-1.51.0-src/library/std/src/panic.rs:344:9
33:        0x109be87a5 - std::panicking::try::do_call::h87407b5b121dda81
    at /private/tmp/rust-20210325-88347-hh2ixd/rustc-1.51.0-src/library/std/src/panicking.rs:379:40
34:        0x109be994d - ___rust_try
35:        0x109be7571 - std::panicking::try::h9ca8a2c4a8f12b2e
    at /private/tmp/rust-20210325-88347-hh2ixd/rustc-1.51.0-src/library/std/src/panicking.rs:343:19
36:        0x109bff071 - std::panic::catch_unwind::ha288698f09a06867
at /private/tmp/rust-20210325-88347-hh2ixd/rustc-1.51.0-src/library/std/src/panic.rs:431:14
37:        0x109af4e1e - std::thread::Builder::spawn_unchecked::{{closure}}::hb9094c88f805ad8d
    at /private/tmp/rust-20210325-88347-hh2ixd/rustc-1.51.0-src/library/std/src/thread/mod.rs:473:30
38:        0x109b02fd1 - core::ops::function::FnOnce::call_once{{vtable.shim}}::hc67c38392b62bbfd
    at /private/tmp/rust-20210325-88347-hh2ixd/rustc-1.51.0-src/library/core/src/ops/function.rs:227:5
39:        0x10b1bbf3b - std::sys::unix::thread::Thread::new::thread_start::h2ede5f70c14488e7
40:     0x7fff20510950 - __pthread_start

thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: SendError("...")', /Users/mrpink/.cargo/registry/src/github.com-1ecc6299db9ec823/librespot-playback-0.1.6/src/player.rs:277:61
stack backtrace:
0:        0x10b1940be - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h04abbaabf148650a
1:        0x10b1d4f6e - core::fmt::write::h14dac7cadec1cc70
2:        0x10b193a7a - std::io::Write::write_fmt::hfaf2e10dfdcc61d8
3:        0x10b1b1979 - std::panicking::default_hook::{{closure}}::h350fee0bf60f2674
4:        0x10b1b14eb - std::panicking::default_hook::h0b4e3bc46e6dcb8d
5:        0x10b1b1f0a - std::panicking::rust_panic_with_hook::h8cdc0a575f4a5a7b
6:        0x10b194885 - std::panicking::begin_panic_handler::{{closure}}::h7a7b30fd1c313876
7:        0x10b194208 - std::sys_common::backtrace::__rust_end_short_backtrace::h2e099be83c81509d
8:        0x10b1b1a83 - _rust_begin_unwind
9:        0x10b1e8c6f - core::panicking::panic_fmt::h4f63e4f6b62b650b
10:        0x10b1e87d5 - core::result::unwrap_failed::hc2a56d017349147e
11:        0x10a58b37c - core::result::Result<T,E>::unwrap::h6a77ca2945061730
    at /private/tmp/rust-20210325-88347-hh2ixd/rustc-1.51.0-src/library/core/src/result.rs:1037:23
12:        0x10a57a334 - librespot_playback::player::Player::command::h0b74f8aaf77bd7db
    at /Users/mrpink/.cargo/registry/src/github.com-1ecc6299db9ec823/librespot-playback-0.1.6/src/player.rs:277:9
13:        0x10a57a479 - librespot_playback::player::Player::stop::h3aa0ba5512a82764
    at /Users/mrpink/.cargo/registry/src/github.com-1ecc6299db9ec823/librespot-playback-0.1.6/src/player.rs:305:9
14:        0x109a559f6 - <ncspot::spotify_worker::Worker as core::future::future::Future>::poll::h4f5421042e49baab
    at /Users/mrpink/Temp-Develop/ncspot/src/spotify_worker.rs:115:25
15:        0x109ad32c5 - <F as futures_core::future::TryFuture>::try_poll::hd1bb110bf466ee2a
    at /Users/mrpink/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-core-0.3.13/src/future.rs:84:9
    16:        0x109c25b15 - <futures_util::compat::compat03as01::Compat<Fut> as futures::future::Future>::poll::{{closure}}::hd6714175e13773f5
    at /Users/mrpink/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.13/src/compat/compat03as01.rs:122:54
17:        0x109c25961 - futures_util::compat::compat03as01::with_context::hcd96dc4a7efbf2ea
    at /Users/mrpink/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.13/src/compat/compat03as01.rs:224:5
18:        0x109c25af1 - <futures_util::compat::compat03as01::Compat<Fut> as futures::future::Future>::poll::h04ab85c76a809fe5 
    at /Users/mrpink/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.13/src/compat/compat03as01.rs:122:9
19:        0x109a06721 - futures::task_impl::Spawn<T>::poll_future_notify::{{closure}}::h75af31fdd2f28fa1
    at /Users/mrpink/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.31/src/task_impl/mod.rs:329:45
20:        0x109a0732f - futures::task_impl::Spawn<T>::enter::{{closure}}::h58f5bcca6c8ed3a4
    at /Users/mrpink/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.31/src/task_impl/mod.rs:399:27
21:        0x109be4f1e - futures::task_impl::std::set::h7a61b92001ea75e6
    at /Users/mrpink/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.31/src/task_impl/std/mod.rs:86:13
22:        0x109a06b20 - futures::task_impl::Spawn<T>::enter::h7cef93b58026229f
    at /Users/mrpink/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.31/src/task_impl/mod.rs:399:9
23:        0x109a06130 - futures::task_impl::Spawn<T>::poll_fn_notify::h65ea82c57aaea3da
    at /Users/mrpink/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.31/src/task_impl/mod.rs:291:9
24:        0x109a065d9 - futures::task_impl::Spawn<T>::poll_future_notify::h651b2476b52afab1
    at /Users/mrpink/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.31/src/task_impl/mod.rs:329:9
25:        0x109a9b2ac - tokio_core::reactor::Core::run::{{closure}}::{{closure}}::{{closure}}::{{closure}}::{{closure}}::h75a1139975b144d1
    at /Users/mrpink/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-core-0.1.18/src/reactor/mod.rs:237:53
26:        0x109bfabc2 - futures::future::lazy::Lazy<F,R>::get::h470f1e5976252960
    at /Users/mrpink/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.31/src/future/lazy.rs:64:59
27:        0x109bfafa1 - <futures::future::lazy::Lazy<F,R> as futures::future::Future>::poll::h1bc86b7198d8872b
    at /Users/mrpink/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.31/src/future/lazy.rs:82:9
28:        0x109a06771 - futures::task_impl::Spawn<T>::poll_future_notify::{{closure}}::haa5a999c18947627
    at /Users/mrpink/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.31/src/task_impl/mod.rs:329:45
29:        0x109a073bf - futures::task_impl::Spawn<T>::enter::{{closure}}::hefb78a1ad3b725eb
    at /Users/mrpink/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.31/src/task_impl/mod.rs:399:27
30:        0x109be502e - futures::task_impl::std::set::hcf7c621d4ae211c0
    at /Users/mrpink/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.31/src/task_impl/std/mod.rs:86:13
31:        0x109a06a00 - futures::task_impl::Spawn<T>::enter::h769e6422d414ee78
    at /Users/mrpink/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.31/src/task_impl/mod.rs:399:9
32:        0x109a060a0 - futures::task_impl::Spawn<T>::poll_fn_notify::h50bc1068bc334e8e
    at /Users/mrpink/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.31/src/task_impl/mod.rs:291:9
33:        0x109a06609 - futures::task_impl::Spawn<T>::poll_future_notify::h9ced4fd310918fb4
    at /Users/mrpink/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.31/src/task_impl/mod.rs:329:9
34:        0x109c390b9 - tokio_current_thread::Entered<P>::block_on::{{closure}}::h905e453a734b2756
    at /Users/mrpink/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-current-thread-0.1.7/src/lib.rs:506:39
35:        0x109c38a25 - tokio_current_thread::Borrow<U>::enter::{{closure}}::{{closure}}::h2acc785582b3d7b4
    at /Users/mrpink/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-current-thread-0.1.7/src/lib.rs:800:40
36:        0x109c387a4 - tokio_current_thread::CurrentRunner::set_spawn::h97dc2cd933c67f15
    at /Users/mrpink/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-current-thread-0.1.7/src/lib.rs:841:9
37:        0x109c38923 - tokio_current_thread::Borrow<U>::enter::{{closure}}::h66c6f980bea1b783
    at /Users/mrpink/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-current-thread-0.1.7/src/lib.rs:800:13
38:        0x109c577b9 - std::thread::local::LocalKey<T>::try_with::h5285561047d9ddc3
    at /private/tmp/rust-20210325-88347-hh2ixd/rustc-1.51.0-src/library/std/src/thread/local.rs:272:16
39:        0x109c572bc - std::thread::local::LocalKey<T>::with::hf5ad2f9b2d52a217
    at /private/tmp/rust-20210325-88347-hh2ixd/rustc-1.51.0-src/library/std/src/thread/local.rs:248:9
40:        0x109c3883b - tokio_current_thread::Borrow<U>::enter::h2ce2e66bb7a25b67
    at /Users/mrpink/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-current-thread-0.1.7/src/lib.rs:798:9
41:        0x109c38ea3 - tokio_current_thread::Entered<P>::block_on::ha8838ec9b73150d0
    at /Users/mrpink/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-current-thread-0.1.7/src/lib.rs:503:23
42:        0x109a9b19a - tokio_core::reactor::Core::run::{{closure}}::{{closure}}::{{closure}}::{{closure}}::h3b2d080a89cb65f2
    at /Users/mrpink/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-core-0.1.18/src/reactor/mod.rs:235:33
43:        0x109944c2b - tokio_timer::timer::handle::with_default::h7b97034b2922f5d8
    at /Users/mrpink/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-timer-0.2.13/src/timer/handle.rs:74:5
44:        0x109a9b123 - tokio_core::reactor::Core::run::{{closure}}::{{closure}}::{{closure}}::h728625801c8d9390
    at /Users/mrpink/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-core-0.1.18/src/reactor/mod.rs:234:29
45:        0x109ad66f4 - tokio_executor::global::with_default::{{closure}}::h56fe651f9dce706d
    at /Users/mrpink/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-executor-0.1.10/src/global.rs:221:9
46:        0x109c5769d - std::thread::local::LocalKey<T>::try_with::h5216ce420651fa98
    at /private/tmp/rust-20210325-88347-hh2ixd/rustc-1.51.0-src/library/std/src/thread/local.rs:272:16
47:        0x109c57055 - std::thread::local::LocalKey<T>::with::h20bf54f105b3e834
    at /private/tmp/rust-20210325-88347-hh2ixd/rustc-1.51.0-src/library/std/src/thread/local.rs:248:9
48:        0x109ad63e2 - tokio_executor::global::with_default::h983de1a681e61bd7
    at /Users/mrpink/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-executor-0.1.10/src/global.rs:190:5
49:        0x109a9b03b - tokio_core::reactor::Core::run::{{closure}}::{{closure}}::h92f7e368d0a23b85
    at /Users/mrpink/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-core-0.1.18/src/reactor/mod.rs:233:25
50:        0x109affbbe - tokio_reactor::with_default::h2fb7e6390f021856
    at /Users/mrpink/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-reactor-0.1.12/src/lib.rs:220:5
51:        0x109a9af93 - tokio_core::reactor::Core::run::{{closure}}::h00d3b2d88302b16c
    at /Users/mrpink/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-core-0.1.18/src/reactor/mod.rs:232:21
52:        0x1099a1181 - scoped_tls::ScopedKey<T>::set::hbbd8ffd9ff3f06e0
    at /Users/mrpink/.cargo/registry/src/github.com-1ecc6299db9ec823/scoped-tls-0.1.2/src/lib.rs:155:9
53:        0x109a9a6f8 - tokio_core::reactor::Core::run::h2e274e4f7f659b4d
    at /Users/mrpink/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-core-0.1.18/src/reactor/mod.rs:231:32
54:        0x109c5d335 - ncspot::spotify::Spotify::worker::h207811396f699678
    at /Users/mrpink/Temp-Develop/ncspot/src/spotify.rs:267:12
55:        0x109b991af - ncspot::spotify::Spotify::start_worker::{{closure}}::he943157e57eb5ca9
    at /Users/mrpink/Temp-Develop/ncspot/src/spotify.rs:129:17
56:        0x109abc373 - std::sys_common::backtrace::__rust_begin_short_backtrace::h7ed996283c24714f
    at /private/tmp/rust-20210325-88347-hh2ixd/rustc-1.51.0-src/library/std/src/sys_common/backtrace.rs:125:18
57:        0x109af6903 - std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}}::h2ef71651da06f0f5
    at /private/tmp/rust-20210325-88347-hh2ixd/rustc-1.51.0-src/library/std/src/thread/mod.rs:474:17
58:        0x109bfe263 - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h06d17fbd52b96728
    at /private/tmp/rust-20210325-88347-hh2ixd/rustc-1.51.0-src/library/std/src/panic.rs:344:9
59:        0x109be8378 - std::panicking::try::do_call::h210415cc2680cf0c
    at /private/tmp/rust-20210325-88347-hh2ixd/rustc-1.51.0-src/library/std/src/panicking.rs:379:40
60:        0x109be994d - ___rust_try
61:        0x109be63f7 - std::panicking::try::h2669abe7ec5980d8
    at /private/tmp/rust-20210325-88347-hh2ixd/rustc-1.51.0-src/library/std/src/panicking.rs:343:19
62:        0x109bfed33 - std::panic::catch_unwind::h63313bc16eb97110
    at /private/tmp/rust-20210325-88347-hh2ixd/rustc-1.51.0-src/library/std/src/panic.rs:431:14
63:        0x109af4b36 - std::thread::Builder::spawn_unchecked::{{closure}}::had043494b248bf94
    at /private/tmp/rust-20210325-88347-hh2ixd/rustc-1.51.0-src/library/std/src/thread/mod.rs:473:30
64:        0x109b02c61 - core::ops::function::FnOnce::call_once{{vtable.shim}}::habe576240d67a510
    at /private/tmp/rust-20210325-88347-hh2ixd/rustc-1.51.0-src/library/core/src/ops/function.rs:227:5
65:        0x10b1bbf3b - std::sys::unix::thread::Thread::new::thread_start::h2ede5f70c14488e7
66:     0x7fff20510950 - __pthread_start
```

[edit] now with complete backlog

**Comment by windowswithoutborders** [comment]
Your debug log isn't mentioning channels, but it is mentioning `Err value: Internal PortAudio error` which is same error I just started getting. Looks like we're both on macOS big sur, with ncspot installed through brew. I'd rollback to 0.4.0 but it doesn't look like I have a local copy anymore and the github servers won't load the commit history for the [ncspot formula.](https://github.com/Homebrew/homebrew-core/blob/master/Formula/ncspot.rb) Does anyone have any troubleshooting suggestions?
```
━||PaMacCore (AUHAL)|| Error on line 1316: err='-66748', msg=Unknown Error┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉┉
 ◼  HBz, Sarah Lahn - Friday Night Lights      thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Internal PortAudio error', /Users/$USER/.cargo/registry/src/github.com-1ecc6299db9ec823/librespot-playback-0.1.6/src/audio_backend/portaudio.rs:86:18        00:00 / 02:55 [100%]
        stack backtrace:
```

**Comment by fdelucchijr** [comment]
Same here, MacOS BigSur with arm64 (m1) processor.
Also, I'm getting very strange behavior with the interface using iterm2 and native terminal also

**Comment by hrkfdn** [comment]
Probably a PortAudio problem. Are you having the same problems with a `rodio_backend` instead of `portaudio_backend` build?

**Comment by elmoritz** [comment]
WOW, Nice community AND with helpful comments😍

So😉
@windowswithoutborders: Sorry for the wrong title, this was the  error message without `RUST_BACKTRACE=full`

@fdelucchijr: I tried the workaround with the broken `portaudio`, but no luck there.
Running native on M1, should be mentioned in the `readme.md` but sadly I have not converted yet

@hrkfdn I rebuild the app with `rodio_backend` instead of `portaudio_backend` but now I don't get a error message, at least not one I can copy-paste here😔

Is there any way to run the app (installed via brew) with the different configurations like `rodio_backend`?

**Comment by elmoritz** [comment]
okay just downloaded the version `0.4.0` for macos and it works without any issues

**Comment by hrkfdn** [comment]
I think the 0.4.0 brew build uses `rodio_backend`? That had different issues, e.g. in #333. Seems to be really hard to find a backend that works for all Macs :( Or maybe it's just PortAudio that needs to be updated/fixed in brew.

**Comment by elmoritz** [comment]
Thank you, as far as I'm concerned the issue can be closed.
I guess there is some more testing to be done to have this working on all macs.

Thank you all for your help.

**Comment by windowswithoutborders** [comment]
Does anyone know how to get the brew formula for 0.4.0 ? Can't get the commit history to load... https://github.com/Homebrew/homebrew-core/blob/master/Formula/ncspot.rb
