### ISSUE TITLE
Panic loading default user state configuration

### ISSUE THREAD

**Issue by chrhasse** [hrkfdn/ncspot#485]
**Describe the bug**
Panics immediately on launch when loading the default userstate configuration, either due to an old, no longer valid file, or no file at all.
```
thread 'main' panicked at 'could not load user state: "Failed serializing value: values must be emitted before tables"', src/config.rs:113:18
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
If a valid `userstate.toml` exists the program will function properly.

**To Reproduce**
1. Build ncspot as of https://github.com/hrkfdn/ncspot/commit/cea5228245d7bc56bd07aab53547881dac03063f
2. Move or delete ~/.config/ncspot/userstate.toml
3. Launch ncspot
4. Observe panic

**Expected behavior**
Program finishes launching.

**System (please complete the following information):**
 - OS: Archlinux
 - Terminal: Termite
 - Version: master
 - Installed from: AUR `ncspot-git`

**Backtrace/Debug log**
```
    Finished dev [unoptimized + debuginfo] target(s) in 8.63s
     Running `target/debug/ncspot`
thread 'main' panicked at 'could not load user state: "Failed serializing value: values must be emitted before tables"', src/config.rs:113:18
stack backtrace:
   0:     0x55b15480b9f0 - std::backtrace_rs::backtrace::libunwind::trace::h5e9d00f0cdf4f57e
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:     0x55b15480b9f0 - std::backtrace_rs::backtrace::trace_unsynchronized::hd5302bd66215dab9
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55b15480b9f0 - std::sys_common::backtrace::_print_fmt::ha0237cd11a34e2bf
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x55b15480b9f0 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h171d4c10df1a98ee
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x55b15483090c - core::fmt::write::h89e4288724daa3fa
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/fmt/mod.rs:1096:17
   5:     0x55b154803d52 - std::io::Write::write_fmt::h6d40f996e84584d9
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/io/mod.rs:1568:15
   6:     0x55b15480dc75 - std::sys_common::backtrace::_print::h0c0b93221682afc8
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x55b15480dc75 - std::sys_common::backtrace::print::h57a9f95204c2fdd6
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x55b15480dc75 - std::panicking::default_hook::{{closure}}::h4245258b50e37e69
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:208:50
   9:     0x55b15480d7d3 - std::panicking::default_hook::h7b00dcc1d0944747
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:225:9
  10:     0x55b15480e411 - std::panicking::rust_panic_with_hook::h71e6a073d87de1f5
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:591:17
  11:     0x55b15480df57 - std::panicking::begin_panic_handler::{{closure}}::hd549436f6bb6dbb8
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:497:13
  12:     0x55b15480be8c - std::sys_common::backtrace::__rust_end_short_backtrace::h4e5f4b72b04174c3
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/sys_common/backtrace.rs:141:18
  13:     0x55b15480deb9 - rust_begin_unwind
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:493:5
  14:     0x55b15482e081 - core::panicking::panic_fmt::hcd56f7f635f62c74
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/panicking.rs:92:14
  15:     0x55b15482dea3 - core::option::expect_none_failed::hf37eebedadde29e6
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/option.rs:1300:5
  16:     0x55b152b8ab1d - core::result::Result<T,E>::expect::h5f45c4ca182f5e09
                               at /home/echo/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/result.rs:997:23
  17:     0x55b152ab5e0d - ncspot::config::Config::new::h1682da6121d0c557
                               at /home/echo/.cache/yay/ncspot-git/src/ncspot/src/config.rs:112:13
  18:     0x55b152ab2413 - ncspot::main::h5b319dee6d0770ae
                               at /home/echo/.cache/yay/ncspot-git/src/ncspot/src/main.rs:173:52
  19:     0x55b152a1b76b - core::ops::function::FnOnce::call_once::h97831054fd88a174
                               at /home/echo/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:227:5
  20:     0x55b152910aee - std::sys_common::backtrace::__rust_begin_short_backtrace::h3ed8ce2f45bea97a
                               at /home/echo/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys_common/backtrace.rs:125:18
  21:     0x55b15285a261 - std::rt::lang_start::{{closure}}::h09d0e5a1d24b6b8d
                               at /home/echo/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/rt.rs:66:18
  22:     0x55b15480e927 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h527fb2333ede305e
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/ops/function.rs:259:13
  23:     0x55b15480e927 - std::panicking::try::do_call::h309d8aee8149866c
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:379:40
  24:     0x55b15480e927 - std::panicking::try::h75a60c31fd16bfc6
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:343:19
  25:     0x55b15480e927 - std::panic::catch_unwind::h1f9892423e99bc00
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panic.rs:431:14
  26:     0x55b15480e927 - std::rt::lang_start_internal::hd5b67df56ca01dae
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/rt.rs:51:25
  27:     0x55b15285a237 - std::rt::lang_start::h040071158899e40d
                               at /home/echo/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/rt.rs:65:5
  28:     0x55b152ab444a - main
  29:     0x7f5c6438eb25 - __libc_start_main
  30:     0x55b15284509e - _start
  31:                0x0 - <unknown>
```

log file is created but empty

**Additional context**
After some debugging, I narrowed the issue down to serializing `QueueState::queue`, specifically when the queue is empty. adding `#[serde(skip_serializing_if = "Vec::is_empty")]` allowed the program to create a `userstate.toml` file correctly, though I am unsure if this is the optimal solution.

**Comment by hrkfdn** [comment]
Fixed by #486
