### ISSUE TITLE
freeze after suspend/resome

### ISSUE THREAD

**Issue by eprst** [hrkfdn/ncspot#552]
Kind of a continuation of https://github.com/hrkfdn/ncspot/issues/536

`master` version (`677a8e0`) was working fine for a while, but today it decided to freeze after resuming from sleep and finishing the buffered track. Looks like it got stuck trying to load next track, UI is completely unresponsive. Stack trace from gdb:
```
#0  0x00007f9759529e29 in syscall () from /lib64/libc.so.6
#1  0x0000562ba9d5edea in std::thread::park ()
#2  0x0000562ba939a8d3 in std::thread::local::LocalKey<T>::with ()
#3  0x0000562ba91fa926 in futures_executor::local_pool::block_on ()
#4  0x0000562ba94c6746 in ncspot::spotify::Spotify::refresh_token ()
#5  0x0000562ba94c593b in ncspot::spotify::Spotify::start_worker ()
#6  0x0000562ba92dcf64 in ncspot::main::_$u7b$$u7b$closure$u7d$$u7d$::hf66b629480604a11 ()
#7  0x0000562ba93b07d3 in tokio::runtime::enter::Enter::block_on ()
#8  0x0000562ba926f265 in tokio::runtime::Runtime::block_on ()
#9  0x0000562ba9388ff2 in ncspot::main ()
#10 0x0000562ba929ae53 in std::sys_common::backtrace::__rust_begin_short_backtrace ()
#11 0x0000562ba94b8539 in std::rt::lang_start::_$u7b$$u7b$closure$u7d$$u7d$::h30f1501b7a390c8a ()
#12 0x0000562ba9d71677 in std::rt::lang_start_internal ()
#13 0x0000562ba93890b2 in main ()
```

I don't think this is easily reproducible

**Comment by hrkfdn** [comment]
Hopefully fixed by #688, so closing this. Feel free to reopen if it still occurs.
