### ISSUE TITLE
Quitting while a track is playing results in thread panic.

### ISSUE THREAD

**Issue by pghvlaans** [hrkfdn/ncspot#663]
**Describe the bug**
Exiting `ncspot` while a track is playing results in `thread <unnamed> panicked` to stdout.

**To Reproduce**
1. Open `ncspot` 
2. Play any track
3. Exit with `q`

**Expected behavior**
No error messaging to stdout when quitting.

**Screenshots**

**System (please complete the following information):**
 - OS: Linux (kernel 5.15.6)
 - Terminal: urxvt, st
 - Version: 0.9.2 (with covers support)
 - Installed from: built from source

**Backtrace/Debug log**
```
$ RUST_BACKTRACE=full ncspot
thread '<unnamed>' panicked at 'could not send no-op event to cursive: "SendError(..)"', src/events.rs:46:14
stack backtrace:
   0:     0x5607d77688b6 - <unknown>
   1:     0x5607d778c47c - <unknown>
   2:     0x5607d7751d75 - <unknown>
   3:     0x5607d77610d0 - <unknown>
   4:     0x5607d7760c71 - <unknown>
   5:     0x5607d7761683 - <unknown>
   6:     0x5607d7768da0 - <unknown>
   7:     0x5607d77689e4 - <unknown>
   8:     0x5607d77611c2 - <unknown>
   9:     0x5607d6d0e091 - <unknown>
  10:     0x5607d6d0df63 - <unknown>
  11:     0x5607d6e8ead0 - <unknown>
  12:     0x5607d701e312 - <unknown>
  13:     0x5607d6de7bd1 - <unknown>
  14:     0x5607d77642e3 - <unknown>
  15:     0x7ff37a6a3e45 - start_thread
  16:     0x7ff37a47a44f - __clone
  17:                0x0 - <unknown>
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Any { .. }', src/library.rs:230:32
stack backtrace:
   0:     0x5607d77688b6 - <unknown>
   1:     0x5607d778c47c - <unknown>
   2:     0x5607d7751d75 - <unknown>
   3:     0x5607d77610d0 - <unknown>
   4:     0x5607d7760c71 - <unknown>
   5:     0x5607d7761683 - <unknown>
   6:     0x5607d7768da0 - <unknown>
   7:     0x5607d77689e4 - <unknown>
   8:     0x5607d77611c2 - <unknown>
   9:     0x5607d6d0e091 - <unknown>
  10:     0x5607d6d0df63 - <unknown>
  11:     0x5607d701e876 - <unknown>
  12:     0x5607d6de6ed1 - <unknown>
  13:     0x5607d77642e3 - <unknown>
  14:     0x7ff37a6a3e45 - start_thread
  15:     0x7ff37a47a44f - __clone
  16:                0x0 - <unknown>
```

**Additional context**
`ncspot` was built with `rust-1.56.1`. The compiler issued the following warnings near the end while compiling `ncspot v0.9.2`:

```
warning: use of deprecated struct `cursive::view::ScrollBase`: `ScrollBase` is being deprecated in favor of the view::scroll module.
 --> src/ui/listview.rs:9:20
  |
9 | use cursive::view::ScrollBase;
  |                    ^^^^^^^^^^
  |
  = note: `#[warn(deprecated)]` on by default

warning: use of deprecated struct `cursive::view::ScrollBase`: `ScrollBase` is being deprecated in favor of the view::scroll module.
  --> src/ui/listview.rs:41:16
   |
41 |     scrollbar: ScrollBase,
   |                ^^^^^^^^^^

warning: use of deprecated struct `cursive::view::ScrollBase`: `ScrollBase` is being deprecated in favor of the view::scroll module.
  --> src/ui/listview.rs:58:24
   |
58 |             scrollbar: ScrollBase::new(),
   |                        ^^^^^^^^^^

warning: associated function is never used: `added_at`
  --> src/model/playable.rs:64:12
   |
64 |     pub fn added_at(&self) -> Option<DateTime<Utc>> {
   |            ^^^^^^^^
   |
   = note: `#[warn(dead_code)]` on by default
```

**Comment by hrkfdn** [comment]
@pghvlaans Hi, could you provide a backtrace of a debug build? Also, what audio backend is this?

**Comment by pghvlaans** [comment]
Evening. It's the PulseAudio backend.

The backtrace is about 12,000 lines long and pasting it in is crashing my browser. Here's everything that came after the authorization stage ended:

    authorization: ***
    [2021-12-10][02:09:23] [rustls::client::tls13] [DEBUG] Ticket saved
    [2021-12-10][02:09:23] [rustls::client::tls13] [DEBUG] Ticket saved
    [2021-12-10][02:09:23] [ureq::unit] [DEBUG] response 200 to GET https://api.spotify.com/v1/me/playlists?limit=50&offset=400
    [2021-12-10][02:09:23] [ureq::pool] [DEBUG] adding stream to pool: https|api.spotify.com|443 -> TcpStream { addr: 
    192.168.10.7:37194, peer: 35.186.224.25:443, fd: 7 }
    [2021-12-10][02:09:23] [ureq::stream] [DEBUG] dropping stream: TcpStream { addr: 192.168.10.7:37194, peer: 35.186.224.25:443, fd: 7 }
    [2021-12-10][02:09:23] [ncspot::ui::pagination] [DEBUG] fetching next page at offset 450
    [2021-12-10][02:09:23] [ncspot::ui::pagination] [DEBUG] paginator is at end
    [2021-12-10][02:09:36] [ncspot::commands] [DEBUG] saving state, 154 items, current track: Some(0)
    [2021-12-10][02:09:36] [ncspot::config] [DEBUG] saving user state to /home/carlson/.config/ncspot/userstate.cbor
    [2021-12-10][02:09:36] [ncspot::spotify_worker] [DEBUG] Worker thread is shutting down, stopping player
    [2021-12-10][02:09:36] [librespot_core::session] [DEBUG] drop Dispatch
    [2021-12-10][02:09:36] [librespot_playback::player] [DEBUG] Shutting down player thread ...
    [2021-12-10][02:09:36] [mio::poll] [TRACE] deregistering event source from poller
    [2021-12-10][02:09:36] [librespot_playback::player] [DEBUG] command=Stop
    [2021-12-10][02:09:36] [librespot_playback::player] [TRACE] == Stopping sink ==
    [2021-12-10][02:09:37] [librespot_playback::player] [DEBUG] drop PlayerInternal[1]
    [2021-12-10][02:09:37] [librespot_core::session] [DEBUG] drop Session[1]
    [2021-12-10][02:09:37] [librespot::component] [DEBUG] drop AudioKeyManager
    [2021-12-10][02:09:37] [librespot::component] [DEBUG] drop MercuryManager
    [2021-12-10][02:09:37] [librespot_playback::player] [DEBUG] PlayerInternal thread finished.

If nothing looks strange there, I'm having a difficult time reproducing the bug at the moment.

**Comment by pghvlaans** [comment]
I think I've figured it out. Rust was upgraded to 1.57.0 on my systems since the original bug report. Binaries built with the newer Rust version aren't showing thread panic.

Sorry if this was a waste of time! Please feel free to close. Thanks for all your hard work on ncspot.

**Comment by hrkfdn** [comment]
No worries, closing it then :)
